### ISSUE TITLE
Integration with supervisor?

### ISSUE THREAD

**Issue by gforcada** [kitconcept/kitconcept.recipe.solr#3]
I thought that the `bin/solr-foreground` would be the right script to use to integrate it with supervisor, and it is halfway.

Supervisor starts solr with no problem and the log entries are correctly shown within supervisor, but when one tries to stop solr with supervisor, it just ignores it, it kills/stops *something*, but solr continues running happily :sweat_smile: 

Which script is one supposed to use for that? :thinking: the previous recipe `collective.recipe.solrinstance` has the `bin/solr-instance` for that.

Any ideas? :thinking:

**Comment by tisto** [comment]
@gforcada Then I guess the right thing to do is to fix "bin/solr-foreground". No idea why it does not work with supervisor though.
